// Generated by scripts/gen-turntable.ts. The start times are frame
// positions in the encoded clip, so hand-editing them drifts the chapter
// track off the video. Run `bun run gen:turntable` instead.
import type { Chapter } from "../types";

export const turntableChapters: Chapter[] = [
  { id: "front", name: "Front", startTime: 0 },
  { id: "detail", name: "Detail", startTime: 8 },
];
